apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pg-datastore"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-f37a03aa"
